# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    omnirob_controller:
      type: mecanum_drive_controller/MecanumDriveController

    omnirob_controller_with_rotation:
      type: mecanum_drive_controller/MecanumDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

omnirob_controller:
  ros__parameters:
    reference_timeout: 0.9

    front_left_wheel_command_joint_name: "fl_wheel_joint"
    front_right_wheel_command_joint_name: "fr_wheel_joint"
    rear_right_wheel_command_joint_name: "br_wheel_joint"
    rear_left_wheel_command_joint_name: "bl_wheel_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.125
      sum_of_robot_center_projection_on_X_Y_axis: 0.589

    base_frame_id: "omnirob_base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true