# Default initial positions for iisy_vgc10's ros2_control fake system

initial_positions:
  arm_joint_1: 0
  arm_joint_2: -1.1523
  arm_joint_3: 2.6179
  arm_joint_4: 0
  arm_joint_5: 0
  arm_joint_6: 0